# Generated by Django 5.0.6 on 2024-06-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_userti_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userti',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users_avatars'),
        ),
        migrations.AlterField(
            model_name='userti',
            name='username',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
