# Generated by Django 5.0.6 on 2024-06-27 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_userti_avatar_alter_userti_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userti',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
